spring:
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: tale-stories-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

grpc:
  server:
    port: 9090

game:
  auth:
    # Тот самый Client ID из Google Console (Backend - Web Application)
    google-client-id: "765238904870-2uh5vglknaivpkl4l1mtl64m3mbajq62.apps.googleusercontent.com"
    # Любая длинная случайная строка для подписи ТВОИХ токенов
    jwt-secret: "my-super-secure-game-secret-key-12345"