spring:
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: tale-stories-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

grpc:
  server:
    port: 9090

game:
  auth:
    # Тот самый Client ID из Google Console (Backend - Web Application)
    google-client-id: ${GOOGLE_OAUTH_CLIENT_ID}
    google-client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
    jwt-secret: "my-super-secure-game-secret-key-12345"