version: '3.8'
services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: talestories-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  session-service:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    container_name: session-service
    depends_on:
      - kafka
      - game-server-builder
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9090:9090"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      GAME_SERVER_IMAGE: "tale-stories-cpp-server:latest"
      DOCKER_HOST: unix:///var/run/docker.sock

  game-server-builder:
    image: tale-stories-cpp-server:latest # Указываем имя, которое будет искать Kotlin
    build:
      context: . # Контекст — корень проекта, чтобы видеть ThirdParty
      dockerfile: DedicatedServer/Dockerfile

    mem_limit: 10g
    memswap_limit: 10g

    environment:
      VCPKG_MAX_CONCURRENCY: 6
      CXXFLAGS: "-O1 -g0"
      CFLAGS: "-O1 -g0"
    # Эта команда просто выводит текст и завершает работу контейнера.
    # Но Docker Compose при запуске проверит, собран ли образ.
    command: [ "echo", "Game Server Image is ready" ]

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

